# FROM node:alpine AS build
FROM node:alpine 
WORKDIR /app
COPY package*.json /app/
RUN npm ci --only=production
COPY . /app/

# WORKDIR ./build
# VOLUME /build_folder

# production
# FROM nginx:alpine
# COPY --from=build /app/build/ /usr/share/nginx/html
# RUN rm /etc/nginx/conf.d/default.conf
# COPY ./nginx.conf /etc/nginx/conf.d
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]