# docker-compose.yml
version: '3'
services:
  database:
    container_name: database
    image: postgres:latest # use latest official postgres version
    restart: always
    env_file:
      - database/database.env # configure postgres
    volumes:
      # - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 8001:5432

  backend:
    container_name: backend
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    depends_on:
      - "database"


  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3001:3000
    stdin_open: true
    command: npm start

# volumes:
#   database-data: # named volumes can be managed easier using docker-compose