# docker-compose.yml
version: '3'
services:
  database:
    container_name: database
    image: postgres:latest # use latest official postgres version
    restart: always
    env_file:
      - database/database.env # configure postgres
    volumes:
      # - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "8001:5432"
volumes:
  database-data: # named volumes can be managed easier using docker-compose
