version: '3'
services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    env_file:
      - ./database/database.env
    volumes:
      - ./database/import/:/tmp/
      # - database-data:/var/lib/postgresql/data/
      # - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh
      
    ports:
      - 5433:5432
    
  backend:
    container_name: backend
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    entrypoint:
      /docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - database
      - frontend


  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    ports:
      - 3000:3000
    # command: npm start
    command: node server
    depends_on:
      - database
