version: '3'
services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    env_file:
      - ./database/database.env
    volumes:
      # - database-data:/var/lib/postgresql/data/
      - ./database/import/:/tmp/:rw
      # - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh
      
    ports:
      - 5433:5432
    
  backend:
    container_name: backend
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    entrypoint:
      /docker-entrypoint.sh
    ports:
      - 8000:8000
    # depends_on:
    #   - frontend


  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    command: npm start
    depends_on:
      - database

# volumes:
#   database-data: