# Generated by Django 3.1.2 on 2020-10-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robob', '0002_add_csv_behaviour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
